# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5                      # Nombre de pages affichées dans la pagination
    default_options:
        page_name: page                 # Nom du paramètre de la requête pour la pagination
        sort_field_name: sort           # Nom du paramètre de tri
        sort_direction_name: direction  # Nom du paramètre de direction de tri
        distinct: true                  # Utiliser DISTINCT pour éviter les doublons
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'