controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: 'attribute'

search_product:
    path: /search/product
    controller: App\Controller\SearchController::recherche
